### PR TITLE
Update to bevy 0.14, usvg 0.42, and several bug fixes

### PR DESCRIPTION
**Pull request by StrikeForceZero**
~~I'm dropping this here in case this helps anyone. It still disappointingly fails to render specific svg's with compounded transforms and text doesn't appear to be working.~~

- updates bevy to 0.14
- updates usvg to 0.42
- fixing several issues like bad transforms
- [adds "basic" gradient support for now instead of dropping the color all together (is just an average of the first and last stop)](https://github.com/user-attachments/assets/53a9992f-469e-4421-8d06-23479246eb18)

- Fix panic in svgs that use path strings and end with a move operation

Knight now renders correctly fixing https://github.com/Weasy666/bevy_svg/issues/37
image

<details>
<summary>Old Details</summary>

image

~~Text stopped rendering with usvg version >=0.38 (not rendering text for resvg cli)~~

image

~~Compounded transforms still broken (working for resvg cli)~~

image

</details>

Renders twinkle (if you fix it by removing the illegal group nodes inside text/tspan or resave in inkscape)
image

Bevy Logo
image

Queen of hearts
image

Averaging of gradients for fallback (instead of showing nothing)
image

### CODE REVIEW

**Comment by StrikeForceZero** [comment]
So I finally figured out why the [transforms were messing with the rendering](https://github.com/Weasy666/bevy_svg/pull/41/commits/4772ed18d3586e9ee0990ac29b4101037a7ebd29). Although, it's fixed every problem I've had with my SVG's it somehow totally butchers the twinkle example. Since fonts aren't working anyway, I might try to backport the required changes to the older version of usvg and see how that turns out.

image

image

**Comment by StrikeForceZero** [comment]
well i was able to [backport the fixes to get the same results](https://github.com/StrikeForceZero/bevy_svg/tree/update_older_usvg) and in the process I realized why text isn't working.

So the only things left for this specific PR would be:
- [ ] Fix this weird offset for some svgs
- [ ] Figure out why twinkle isn't rendering properly

**Comment by StrikeForceZero** [comment]
Ok I think this is mostly at least feature parity or even improving since it's last release (besides the text handling regression from upgrading usbg on the twinkle example.)

I'm going to do some more experimenting this weekend and see if I can find a way to properly reconstruct the twinkle SVG with the data that's being parsed before I take it out of draft, but anyone is welcome to review/test it with other svgs as is.

**Comment by Weasy666** [comment]
Ok... wow. Thanks for the amazing work you are putting into this. 🙏
And sorry for my radio silence. I am a bit overwhelmed with work and was burned out a bit in regard to chasing Bevy releases and the constant changes to rendering.
I'll start to review this in the coming days.

**Comment by StrikeForceZero** [comment]
> Ok... wow. Thanks for the amazing work you are putting into this. 🙏 And sorry for my radio silence. I am a bit overwhelmed with work and was burned out a bit in regard to chasing Bevy releases and the constant changes to rendering. I'll start to review this in the coming days.

No worries, take your time. I'm just happy to have finally chased down most of the problems I've had trying to get non-rasterized SVG support working in Bevy :)

**Comment by Weasy666** [comment]
Looking good to me!
Thank you very much for the work you have put into this! I'll publish a new version after the merge. So, expect it on crates.io in about half an hour 🙂

**Pull request merged**
