### PR TITLE
Change license to dual license model

### PR DESCRIPTION
**Pull request by Weasy666**
This PR changes the license model from a single `Apache` license to a dual license model with the `Apache` and `MIT` licenses.

The following persons need to approve this change:
- [x] @Weasy666 
- [x] @neosam
- [x] @mdevlamynck 
- [x] @RomainMazB 

Please write a comment here, in which you approve the change. Thank you all 😃

### CODE REVIEW

**Comment by Weasy666** [comment]
I hereby approve the license change

**Comment by neosam** [comment]
I approve the license change to the dual license model with the Apache and MIT licenses.

**Comment by RomainMazB** [comment]
I approve.

**Comment by mdevlamynck** [comment]
I approve.

**Comment by Weasy666** [comment]
Thank you all very much! 😃🙇‍♂️

**Pull request merged**
