### PR TITLE
Port to Bevy 0.9

### PR DESCRIPTION
**Pull request by tasgon**
Basically the title. I also ran `cargo fmt` while working on some changes, which formatted the entire repo. I can try to revert that if you'd like.

### CODE REVIEW

**Comment by Weasy666** [comment]
Thank you for doing this 🙂 I would like to ask you, to please separate the actual changes needed for Bevy 0.9 compatibility from the massive formatting changes you did. It is unnecessarily arduous to differentiate between them while reviewing the PR.

**Comment by tasgon** [comment]
Actually, if you wouldn't mind, could you `cargo fmt` the current main branch? It should be simpler for me to rebase off of that and it will make it easier for others to contribute to this repo as well.

**Comment by Weasy666** [comment]
Good idea, and done!

**Comment by Weasy666** [comment]
Thank you very much for doing this. I will most likely not release the new crate version right away. I have the next 2 weeks off and want to refactor the crate and try to remove the origin hack.

**Pull request merged**
